version: '3.9'

services:

  web:
    image: spruha29/spruha-thesis-repo1:djangoapp
    restart: unless-stopped  
    ports:
        - :80
    volumes:
    - static_volume:/path/to/static/files
    - media_volume:/path/to/media/files
    
   # command: /app/path/inside/container/custom-start-script


    deploy:
      resources:
        limits:
          memory: 2G
      replicas: 3
      placement:
        constraints:
            - node.role==worker
      
volumes:
  static_volume:
  media_volume: